import { labels, layers, namedTheme } from 'protomaps-themes-base'
import type { StyleSpecification } from 'maplibre-gl'

// Local extract of Protomaps' daily build, scoped to the Metro Vancouver bbox,
// generated by `npm run prepare-basemap`. We serve it from the same origin
// because the upstream build bucket isn't CORS-enabled for browsers. Prod
// will override this via VITE_PMTILES_URL to point at an R2-hosted archive.
const DEFAULT_PMTILES_URL = '/data/basemap.pmtiles'

export function getPmtilesUrl(): string {
  return import.meta.env.VITE_PMTILES_URL || DEFAULT_PMTILES_URL
}

// Basemap style built from Protomaps' default layer set. `theme` picks the
// paint ramp — 'dark' keeps the original colored-routes-on-muted-slate look;
// 'light' is used by the light-mode toggle (feature 12). Label fonts are
// loaded from Protomaps' public glyph endpoint; they can be self-hosted later.
//
// `layers()` and `labels()` are split in protomaps-themes-base v4+ — the
// former emits fill/line paint, the latter emits symbol layers. We merge
// both so street and place names render; transit layers get added above
// these by Map.tsx so colored route lines always sit on top.
export function buildMapStyle(
  pmtilesUrl: string,
  theme: 'dark' | 'light' = 'dark',
): StyleSpecification {
  return {
    version: 8,
    glyphs: 'https://protomaps.github.io/basemaps-assets/fonts/{fontstack}/{range}.pbf',
    sources: {
      protomaps: {
        type: 'vector',
        url: `pmtiles://${pmtilesUrl}`,
        attribution: '© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>',
      },
    },
    layers: [
      ...layers('protomaps', namedTheme(theme)),
      ...labels('protomaps', theme, 'en', 'Latin'),
    ],
  }
}
