import { layers, namedTheme } from 'protomaps-themes-base'
import type { StyleSpecification } from 'maplibre-gl'

// Local extract of Protomaps' daily build, scoped to the Metro Vancouver bbox,
// generated by `npm run prepare-basemap`. We serve it from the same origin
// because the upstream build bucket isn't CORS-enabled for browsers. Prod
// will override this via VITE_PMTILES_URL to point at an R2-hosted archive.
const DEFAULT_PMTILES_URL = '/data/basemap.pmtiles'

export function getPmtilesUrl(): string {
  return import.meta.env.VITE_PMTILES_URL || DEFAULT_PMTILES_URL
}

// Dark basemap style with all Protomaps default layers. Label fonts are
// loaded from Protomaps' public glyph endpoint; they can be self-hosted later.
export function buildMapStyle(pmtilesUrl: string): StyleSpecification {
  return {
    version: 8,
    glyphs: 'https://protomaps.github.io/basemaps-assets/fonts/{fontstack}/{range}.pbf',
    sources: {
      protomaps: {
        type: 'vector',
        url: `pmtiles://${pmtilesUrl}`,
        attribution: '© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>',
      },
    },
    layers: layers('protomaps', namedTheme('dark')),
  }
}
